name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Server Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: false
          tags: word-of-wisdom-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Client Image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: false
          tags: word-of-wisdom-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker Compose
        run: |
          docker-compose config
          echo "Docker Compose configuration is valid"