name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint Client
        run: cd client && golangci-lint run ./... --timeout=5m

      - name: Lint Server
        run: cd server && golangci-lint run ./... --timeout=5m
  test-client:
    name: Test Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: client/go.sum

      - name: Download dependencies
        run: cd client && go mod download

      - name: Test Client
        run: cd client && go test -v ./...

  test-server:
    name: Test Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: server/go.sum

      - name: Download dependencies
        run: cd server && go mod download

      - name: Test Server
        run: cd server && go test -v ./...

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Client Coverage
        run: |
          cd client
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Server Coverage
        run: |
          cd server
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

  tests-passed:
    name: All Tests Passed
    needs: [lint, test-client, test-server, coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Tests Passed
        run: echo "All tests passed successfully!"